#
#  Do not edit this file.  This file is generated from 
#  package.bld.  Any modifications to this file will be 
#  overwritten whenever makefiles are re-generated.
#
#  target compatibility key = ti.targets.arm.elf.M4F{1,0,15.12,1
#
RTOS_16eth_clean.xem4f: package/cfg/RTOS_16eth_clean.xem4f.mak

clean::
	-$(RM) package/cfg/RTOS_16eth_clean.xem4f.mak
